version: '3'

services:
  # backend:
  #   build: ./backend
  #   ports:
  #     - "1337:1337"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   networks:
  #     - pong-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    # depends_on:
    #   - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - pong-network

  # db:
  #   image: postgres
  #   env_file:
  #     - .env
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   networks:
  #     - pong-network

volumes:
  db-data:

networks:
  pong-network:
