version: '3.1'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    env_file: 
      - .env
    ports:
      - "5432:5432"
    networks:
      - web
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

    restart: always

  # backend-app:
  #   build: ./backend
  #   container_name: nestjs
  #   depends_on:
  #     - postgres-db
  #   env_file: 
  #     - .env
  #   ports:
  #     - "1337:1337"
  #   networks:
  #     - web
  #   restart: always

  # frontend-app:
  #   build: ./frontend
  #   container_name: nextjs
  #   depends_on:
  #     - backend-app
  #   env_file: 
  #     - .env
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - web
  #   restart: always

networks:
  web:
    name: web
    driver: bridge

volumes:
  postgres_data:
