version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file: 
      - .env
    ports:
      - 5432:5432
    networks:
      - web
    volumes:
      - postgres_data:/Users/mountassir/Desktop/docker-db/
    restart: always
  nestjs:
    build: ./backend
    container_name: nestjs
    depends_on:
      - postgres
    env_file: 
      - .env
    ports:
      - 1337:1337
    networks:
      - web
    restart: always
  nextjs:
    build: ./frontend
    container_name: nextjs
    depends_on:
      - nestjs
    env_file: 
      - .env
    ports:
      - 3000:3000
    networks:
      - web
    restart: always
networks:
  web:
    name: web
    driver: bridge
volumes:
  postgres_data: